export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
export const ADD_NOTIFICATIONS = 'ADD_NOTIFICATIONS'
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS'
export const VIEW_NOTIFICATION = 'VIEW_NOTIFICATION'